-- Report : List of Products
SELECT * FROM products;

-- Report : Sales Report by Product
SELECT product_name, SUM(units) AS total_units, SUM(total) AS total_sales
FROM orders
GROUP BY product_name;

-- Report : User Report
SELECT id, fname, lname, email, address, city, pin
FROM users
WHERE type = 'user';

-- Report : Daily Sales Report
SELECT DATE(date) AS sales_date, SUM(total) AS daily_sales
FROM orders
GROUP BY sales_date;

-- Report : Out of Stock Report
SELECT product_name, qty
FROM products
WHERE qty = 0;


-- Report : Display all orders with their respective products, quantities, and total amount:

SELECT o.id, o.product_name, o.units, o.total, p.product_code, p.product_desc, p.price
FROM orders o
INNER JOIN products p ON o.product_code = p.product_code;


-- Report : Show the top 5 most ordered products:


SELECT p.product_name, SUM(o.units) as total_units
FROM orders o
INNER JOIN products p ON o.product_code = p.product_code
GROUP BY p.product_name
ORDER BY total_units DESC
LIMIT 5;


-- Report : Display all users and their respective orders:

SELECT u.fname, u.lname, u.email, o.product_name, o.units, o.total
FROM users u
INNER JOIN orders o ON u.email = o.email;



-- Report : Show the total revenue generated by each product:

SELECT p.product_name, SUM(o.total) as revenue
FROM orders o
INNER JOIN products p ON o.product_code = p.product_code
GROUP BY p.product_name;


--example
SELECT
    orders.order_id,
    orders.order_date,
    customers.customer_name,
    SUM(order_items.quantity * order_items.unit_price) AS total_price,
    CONCAT('<a href=\"order_details.php?order_id=', orders.order_id, '\">View Details</a>') AS details_link
FROM
    orders
INNER JOIN
    customers ON orders.customer_id = customers.customer_id
INNER JOIN
    order_items ON orders.order_id = order_items.order_id
GROUP BY
    orders.order_id
